name: E2E Regression Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '00 4 * * *'
  workflow_dispatch:


env:
  TESTING_SCOPE: "com.automationexercise.tests.TC*"

jobs:

  E2E_Chrome_Linux_Test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      checks: write
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.6

      - name: Set permissions for github.workspace
        run: sudo chmod -R 777 $GITHUB_WORKSPACE

      - name: Download Allure History from gh-pages
        continue-on-error: true
        run: |
          git config --global user.email "ahmedashraaf09@gmail.com"
          git config --global user.name "Ashraaf7"
          git clone --depth=1 --branch gh-pages https://github.com/${{ github.repository }}.git gh-pages
          mkdir -p ./test-outputs/allure-results/
          cp -r gh-pages/Linux/history ./test-outputs/allure-results/ || echo "No history yet"

      - name: Run Tests
        continue-on-error: true
        run: mvn -DbrowserType="Chrome" -DexecutionType="LocalHeadless" -DOpenAllureReportAfterExecution="false" -Dtest="com.automationexercise.tests.TC*" clean test

      - name: Update Allure History on gh-pages
        continue-on-error: true
        run: |
          git config --global user.email "ahmedashraaf09@gmail.com"
          git config --global user.name "ashraf"

          # Remove existing history if it exists (to avoid overwrite error)
          if (Test-Path "./gh-pages/Linux/history") {
            Remove-Item -Recurse -Force "./gh-pages/Linux/history"
          }

          # Now safely copy the new history
          Copy-Item -Recurse -Force "./test-outputs/full-report/history" "./gh-pages/Linux/history"

          cd gh-pages
          git add Linux/
          git commit -m "Update Linux history from CI run [skip ci]" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin gh-pages
        shell: pwsh


      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Chrome_Linux_Allure
          path: "test-outputs/reports/*.html"



  E2E_Edge_Windows_Test:
    runs-on: windows-latest
    permissions:
      contents: write
      issues: write
      checks: write
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.6

      - name: Download Allure History from gh-pages
        continue-on-error: true
        run: |
          git config --global user.email "ahmedashraaf09@gmail.com"
          git config --global user.name "Ashraaf7"
          git clone --depth=1 --branch gh-pages https://github.com/${{ github.repository }}.git gh-pages
          mkdir -p ./test-outputs/allure-results/
          cp -r gh-pages/windows/history ./test-outputs/allure-results/ || echo "No history yet"

      - name: Run Tests
        continue-on-error: true
        run: mvn -DbrowserType="Edge" -DexecutionType="LocalHeadless" -DOpenAllureReportAfterExecution="false" -Dtest="com.automationexercise.tests.TC*"  clean test

      - name: Update Allure History on gh-pages
        continue-on-error: true
        run: |
          git config --global user.email "ahmedashraaf09@gmail.com"
          git config --global user.name "ashraf"

          # Remove existing history if it exists (to avoid overwrite error)
          if (Test-Path "./gh-pages/windows/history") {
            Remove-Item -Recurse -Force "./gh-pages/windows/history"
          }

          # Now safely copy the new history
          Copy-Item -Recurse -Force "./test-outputs/full-report/history" "./gh-pages/windows/history"

          cd gh-pages
          git add windows/
          git commit -m "Update win history from CI run [skip ci]" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin gh-pages
        shell: pwsh



      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Edge_Windows_Allure
          path: "test-outputs/reports/*.html"

