name: E2E Regression Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '00 4 * * *'
  workflow_dispatch:


env:
  TESTING_SCOPE: "com.automationexercise.tests.TC*"

jobs:

  E2E_Chrome_Linux_Test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      checks: write
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.6

      - name: Set permissions for github.workspace
        run: sudo chmod -R 777 $GITHUB_WORKSPACE

      - name: Download Allure History
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: allure-history
          path: ./test-outputs/allure-results/history

      - name: Run Tests
        continue-on-error: true
        run: mvn -DbrowserType="Chrome" -DexecutionType="LocalHeadless" -DOpenAllureReportAfterExecution="false" -Dtest="com.automationexercise.tests.TC*" clean test

      - name: Upload Allure History
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: allure-history
          path: ./test-outputs/full-report/history


      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Chrome_Linux_Allure
          path: "test-outputs/reports/*.html"



  E2E_Edge_Windows_Test:
    runs-on: windows-latest
    permissions:
      contents: write
      issues: write
      checks: write
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.6

      - name: Download Allure History
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: allure-history
          path: ./test-outputs/allure-results/history

      - name: Run Tests
        continue-on-error: true
        run: mvn -DbrowserType="Edge" -DexecutionType="LocalHeadless" -DOpenAllureReportAfterExecution="false" -Dtest="com.automationexercise.tests.TC*"  clean test

      - name: Upload Allure History
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: allure-history
          path: ./test-outputs/full-report/history

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Edge_Windows_Allure
          path: "test-outputs/reports/*.html"

