name: E2E Regression Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '00 4 * * *'
  workflow_dispatch:


env:
  TESTING_SCOPE: "%regex[com.automationexercise.tests.*],!%regex[com.automationexercise.tests.BaseTest]"

jobs:

  E2E_Chrome_Linux_Test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      checks: write
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.6


      - name: Run Tests
        continue-on-error: true
        run: mvn -DbrowserType="Chrome" -DexecutionType="LocalHeadless" -DOpenAllureReportAfterExecution="false" -Dtest="${TESTING_SCOPE}" clean test


      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Chrome_Linux_Allure
          path: "test-outputs/reports/*.html"



  E2E_Edge_Windows_Test:
    runs-on: windows-latest
    permissions:
      contents: write
      issues: write
      checks: write
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.6

      - name: Print TESTING_SCOPE
        run: echo $TESTING_SCOPE

      - name: Run Tests
        continue-on-error: true
        run: mvn -DbrowserType="Edge" -DexecutionType="LocalHeadless" -DOpenAllureReportAfterExecution="false" -Dtest="${TESTING_SCOPE}"  clean test

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Edge_Windows_Allure
          path: "test-outputs/reports/*.html"

